const data = {
	products: [
		{
			name: "Apple",
			slug: "apple",
			category: "fruits",
			image: "/images/apple.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Apple",
		},
		{
			name: "Broccoli",
			slug: "broccoli",
			category: "vegetables",
			image: "/images/broccoli.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Broccoli",
		},
		{
			name: "coconut",
			slug: "coconet",
			category: "fruits",
			image: "/images/coconet.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Apples",
		},
		{
			name: "Grassbean",
			slug: "grassbean",
			category: "Vegetables",
			image: "/images/grassbean.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Grassbean",
		},
		{
			name: "Guava",
			slug: "guava",
			category: "fruits",
			image: "/images/guava.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Guava",
		},
		{
			name: "Litchi",
			slug: "litchi",
			category: "fruits",
			image: "/images/litchi.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Litchi",
		},
		{
			name: "Onion",
			slug: "onion",
			category: "vegetables",
			image: "/images/onion.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Onion",
		},
		{
			name: "Pepper",
			slug: "pepper",
			category: "vegetables",
			image: "/images/pepper.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Pepper",
		},
		{
			name: "Tomato",
			slug: "tomato",
			category: "fruits",
			image: "/images/tomato.jpg",
			price: 170,
			rating: "4",
			numReviews: 7,
			countStock: 19,
			description: "Fresh natural Tomato",
		},
	],
};
export default data;
